export const queryKeys = {
  users: (search: string, page: number) => ['users', search, page] as const,
  user: (id: string) => ['user', id] as const,
  deletionRequests: ['deletionRequests'] as const,
  content: ['content'] as const,
  business: (search: string, page: number) => ['business', search, page] as const,
  businessDetail: (id: string) => ['businessDetail', id] as const,
  analyticsOverview: ['analyticsOverview'] as const,
  pricing: ['pricing'] as const,
  auditLog: (page: number, pageSize: number) => ['auditLog', page, pageSize] as const,
  config: ['config'] as const,
  ships: (status: string, page: number) => ['ships', status, page] as const,
  townSquareSessions: (page: number) => ['townSquareSessions', page] as const,
  townSquarePairings: (sessionId: string) => ['townSquarePairings', sessionId] as const,
};
