// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MinglDingl.Engine.Data.Migrations
{
    // SQL-only: the partial index is not part of the EF model, so the snapshot is unchanged.
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915000000_AddOathProvenOnceEverIndex")]
    partial class AddOathProvenOnceEverIndex
    {
    }
}
