// Generated by scripts/gen-brush.js — do not edit; rerun the script instead.

import type { ImageSourcePropType } from 'react-native';

/** The Seek card's gem line along its top, dry-brushed: a white mask, tinted the gem. */
export const BRUSH_CARD_EDGE: ImageSourcePropType = require('../../assets/brush/card-edge.png');
export const BRUSH_CARD_EDGE_ASPECT = 12.5;
/** The Seek card's line over its buttons: a white mask. */
export const BRUSH_CARD_RULE: ImageSourcePropType = require('../../assets/brush/card-rule.png');
export const BRUSH_CARD_RULE_ASPECT = 50;
/** The open ring behind the Seek card's seal: a white mask. */
export const BRUSH_CARD_RING: ImageSourcePropType = require('../../assets/brush/card-ring.png');

/** The trail to the next gem: one even stroke, a white mask drawn bare and inked over. */
export const BRUSH_TRAIL: ImageSourcePropType = require('../../assets/brush/trail.png');
export const BRUSH_TRAIL_ASPECT = 35;

/** `SectionDivider`'s line: a hair at the left, full at the right; mirrored for the other side. */
export const BRUSH_RULE: ImageSourcePropType = require('../../assets/brush/rule.png');

/** The portrait frame for each rung, `TIER_ORDER` order: a 160pt box centred on the 118pt avatar. */
export const BRUSH_FRAMES: readonly ImageSourcePropType[] = [require('../../assets/brush/frame-0.png'), require('../../assets/brush/frame-1.png'), require('../../assets/brush/frame-2.png'), require('../../assets/brush/frame-3.png'), require('../../assets/brush/frame-4.png'), require('../../assets/brush/frame-5.png')];

/** Numerals, two hands of each (`${digit}-${hand}`), as white masks with their width over height.
 *  The comma is one dab. */
export const BRUSH_DIGITS: Record<string, { source: ImageSourcePropType; aspect: number }> = {
  '0-0': { source: require('../../assets/brush/digit-0-0.png'), aspect: 0.6406 },
  '0-1': { source: require('../../assets/brush/digit-0-1.png'), aspect: 0.6406 },
  '1-0': { source: require('../../assets/brush/digit-1-0.png'), aspect: 0.4453 },
  '1-1': { source: require('../../assets/brush/digit-1-1.png'), aspect: 0.4453 },
  '2-0': { source: require('../../assets/brush/digit-2-0.png'), aspect: 0.7031 },
  '2-1': { source: require('../../assets/brush/digit-2-1.png'), aspect: 0.7031 },
  '3-0': { source: require('../../assets/brush/digit-3-0.png'), aspect: 0.6406 },
  '3-1': { source: require('../../assets/brush/digit-3-1.png'), aspect: 0.6406 },
  '4-0': { source: require('../../assets/brush/digit-4-0.png'), aspect: 0.7188 },
  '4-1': { source: require('../../assets/brush/digit-4-1.png'), aspect: 0.7188 },
  '5-0': { source: require('../../assets/brush/digit-5-0.png'), aspect: 0.6641 },
  '5-1': { source: require('../../assets/brush/digit-5-1.png'), aspect: 0.6641 },
  '6-0': { source: require('../../assets/brush/digit-6-0.png'), aspect: 0.6406 },
  '6-1': { source: require('../../assets/brush/digit-6-1.png'), aspect: 0.6406 },
  '7-0': { source: require('../../assets/brush/digit-7-0.png'), aspect: 0.6875 },
  '7-1': { source: require('../../assets/brush/digit-7-1.png'), aspect: 0.6875 },
  '8-0': { source: require('../../assets/brush/digit-8-0.png'), aspect: 0.6641 },
  '8-1': { source: require('../../assets/brush/digit-8-1.png'), aspect: 0.6641 },
  '9-0': { source: require('../../assets/brush/digit-9-0.png'), aspect: 0.6484 },
  '9-1': { source: require('../../assets/brush/digit-9-1.png'), aspect: 0.6484 },
  ',': { source: require('../../assets/brush/digit-comma.png'), aspect: 0.2813 },
};
/** The share of a numeral's bake left as margin above and below its ink. */
export const BRUSH_DIGIT_PAD = 0.1;

/** Ink pools for under a room's name: full colour with alpha, 900×240. */
export const BRUSH_POOLS: readonly ImageSourcePropType[] = [require('../../assets/brush/pool-0.png'), require('../../assets/brush/pool-1.png'), require('../../assets/brush/pool-2.png'), require('../../assets/brush/pool-3.png')];
export const BRUSH_POOL_ASPECT = 3.75;

/** The ink-wash passage: `BRUSH_WASH_FRAMES` frames side by side, clear to covered. */
export const BRUSH_WASH: ImageSourcePropType = require('../../assets/brush/wash.png');
export const BRUSH_WASH_FRAMES = 14;
