// Generated by scripts/gen-glyphs.js from the GLYPHS table in ./Glyph.tsx — rerun it, never edit this.
import type { ImageSourcePropType } from 'react-native';
import type { GlyphName } from './Glyph';

/** The pixel sizes each glyph is baked at; `Glyph` picks the smallest that covers the screen size. */
export const GLYPH_PIXELS = [48, 96, 192] as const;

export const GLYPH_IMAGES: Record<GlyphName, Record<(typeof GLYPH_PIXELS)[number], ImageSourcePropType>> = {
  fire: { 48: require('../../assets/glyphs/fire-48.png'), 96: require('../../assets/glyphs/fire-96.png'), 192: require('../../assets/glyphs/fire-192.png') },
  letters: { 48: require('../../assets/glyphs/letters-48.png'), 96: require('../../assets/glyphs/letters-96.png'), 192: require('../../assets/glyphs/letters-192.png') },
  lantern: { 48: require('../../assets/glyphs/lantern-48.png'), 96: require('../../assets/glyphs/lantern-96.png'), 192: require('../../assets/glyphs/lantern-192.png') },
  forge: { 48: require('../../assets/glyphs/forge-48.png'), 96: require('../../assets/glyphs/forge-96.png'), 192: require('../../assets/glyphs/forge-192.png') },
  gem: { 48: require('../../assets/glyphs/gem-48.png'), 96: require('../../assets/glyphs/gem-96.png'), 192: require('../../assets/glyphs/gem-192.png') },
  ice: { 48: require('../../assets/glyphs/ice-48.png'), 96: require('../../assets/glyphs/ice-96.png'), 192: require('../../assets/glyphs/ice-192.png') },
  seal: { 48: require('../../assets/glyphs/seal-48.png'), 96: require('../../assets/glyphs/seal-96.png'), 192: require('../../assets/glyphs/seal-192.png') },
  seals: { 48: require('../../assets/glyphs/seals-48.png'), 96: require('../../assets/glyphs/seals-96.png'), 192: require('../../assets/glyphs/seals-192.png') },
  knot: { 48: require('../../assets/glyphs/knot-48.png'), 96: require('../../assets/glyphs/knot-96.png'), 192: require('../../assets/glyphs/knot-192.png') },
  flame: { 48: require('../../assets/glyphs/flame-48.png'), 96: require('../../assets/glyphs/flame-96.png'), 192: require('../../assets/glyphs/flame-192.png') },
  pledge: { 48: require('../../assets/glyphs/pledge-48.png'), 96: require('../../assets/glyphs/pledge-96.png'), 192: require('../../assets/glyphs/pledge-192.png') },
  candle: { 48: require('../../assets/glyphs/candle-48.png'), 96: require('../../assets/glyphs/candle-96.png'), 192: require('../../assets/glyphs/candle-192.png') },
  bell: { 48: require('../../assets/glyphs/bell-48.png'), 96: require('../../assets/glyphs/bell-96.png'), 192: require('../../assets/glyphs/bell-192.png') },
  hearth: { 48: require('../../assets/glyphs/hearth-48.png'), 96: require('../../assets/glyphs/hearth-96.png'), 192: require('../../assets/glyphs/hearth-192.png') },
};
