// Generated by scripts/gen-glyphs.js from the GLYPHS table in ./Glyph.tsx — rerun it, never edit this.
import type { ImageSourcePropType } from 'react-native';
import type { GlyphName } from './Glyph';

/** The pixel sizes each glyph is baked at; `Glyph` picks the smallest that covers the screen size. */
export const GLYPH_PIXELS = [48, 96, 192] as const;

export const GLYPH_IMAGES: Record<GlyphName, Record<(typeof GLYPH_PIXELS)[number], ImageSourcePropType>> = {
  fire: { 48: require('../../assets/glyphs/fire-48.png'), 96: require('../../assets/glyphs/fire-96.png'), 192: require('../../assets/glyphs/fire-192.png') },
  letters: { 48: require('../../assets/glyphs/letters-48.png'), 96: require('../../assets/glyphs/letters-96.png'), 192: require('../../assets/glyphs/letters-192.png') },
  lantern: { 48: require('../../assets/glyphs/lantern-48.png'), 96: require('../../assets/glyphs/lantern-96.png'), 192: require('../../assets/glyphs/lantern-192.png') },
  forge: { 48: require('../../assets/glyphs/forge-48.png'), 96: require('../../assets/glyphs/forge-96.png'), 192: require('../../assets/glyphs/forge-192.png') },
  gem: { 48: require('../../assets/glyphs/gem-48.png'), 96: require('../../assets/glyphs/gem-96.png'), 192: require('../../assets/glyphs/gem-192.png') },
  ice: { 48: require('../../assets/glyphs/ice-48.png'), 96: require('../../assets/glyphs/ice-96.png'), 192: require('../../assets/glyphs/ice-192.png') },
  seal: { 48: require('../../assets/glyphs/seal-48.png'), 96: require('../../assets/glyphs/seal-96.png'), 192: require('../../assets/glyphs/seal-192.png') },
  seals: { 48: require('../../assets/glyphs/seals-48.png'), 96: require('../../assets/glyphs/seals-96.png'), 192: require('../../assets/glyphs/seals-192.png') },
  knot: { 48: require('../../assets/glyphs/knot-48.png'), 96: require('../../assets/glyphs/knot-96.png'), 192: require('../../assets/glyphs/knot-192.png') },
  flame: { 48: require('../../assets/glyphs/flame-48.png'), 96: require('../../assets/glyphs/flame-96.png'), 192: require('../../assets/glyphs/flame-192.png') },
  pledge: { 48: require('../../assets/glyphs/pledge-48.png'), 96: require('../../assets/glyphs/pledge-96.png'), 192: require('../../assets/glyphs/pledge-192.png') },
  candle: { 48: require('../../assets/glyphs/candle-48.png'), 96: require('../../assets/glyphs/candle-96.png'), 192: require('../../assets/glyphs/candle-192.png') },
  bell: { 48: require('../../assets/glyphs/bell-48.png'), 96: require('../../assets/glyphs/bell-96.png'), 192: require('../../assets/glyphs/bell-192.png') },
  hearth: { 48: require('../../assets/glyphs/hearth-48.png'), 96: require('../../assets/glyphs/hearth-96.png'), 192: require('../../assets/glyphs/hearth-192.png') },
  oath: { 48: require('../../assets/glyphs/oath-48.png'), 96: require('../../assets/glyphs/oath-96.png'), 192: require('../../assets/glyphs/oath-192.png') },
  'thread-1': { 48: require('../../assets/glyphs/thread-1-48.png'), 96: require('../../assets/glyphs/thread-1-96.png'), 192: require('../../assets/glyphs/thread-1-192.png') },
  'thread-2': { 48: require('../../assets/glyphs/thread-2-48.png'), 96: require('../../assets/glyphs/thread-2-96.png'), 192: require('../../assets/glyphs/thread-2-192.png') },
  'thread-3': { 48: require('../../assets/glyphs/thread-3-48.png'), 96: require('../../assets/glyphs/thread-3-96.png'), 192: require('../../assets/glyphs/thread-3-192.png') },
  horn: { 48: require('../../assets/glyphs/horn-48.png'), 96: require('../../assets/glyphs/horn-96.png'), 192: require('../../assets/glyphs/horn-192.png') },
  clasp: { 48: require('../../assets/glyphs/clasp-48.png'), 96: require('../../assets/glyphs/clasp-96.png'), 192: require('../../assets/glyphs/clasp-192.png') },
  dawn: { 48: require('../../assets/glyphs/dawn-48.png'), 96: require('../../assets/glyphs/dawn-96.png'), 192: require('../../assets/glyphs/dawn-192.png') },
  mended: { 48: require('../../assets/glyphs/mended-48.png'), 96: require('../../assets/glyphs/mended-96.png'), 192: require('../../assets/glyphs/mended-192.png') },
  map: { 48: require('../../assets/glyphs/map-48.png'), 96: require('../../assets/glyphs/map-96.png'), 192: require('../../assets/glyphs/map-192.png') },
  bow: { 48: require('../../assets/glyphs/bow-48.png'), 96: require('../../assets/glyphs/bow-96.png'), 192: require('../../assets/glyphs/bow-192.png') },
  moon: { 48: require('../../assets/glyphs/moon-48.png'), 96: require('../../assets/glyphs/moon-96.png'), 192: require('../../assets/glyphs/moon-192.png') },
  'chest-open': { 48: require('../../assets/glyphs/chest-open-48.png'), 96: require('../../assets/glyphs/chest-open-96.png'), 192: require('../../assets/glyphs/chest-open-192.png') },
  quill: { 48: require('../../assets/glyphs/quill-48.png'), 96: require('../../assets/glyphs/quill-96.png'), 192: require('../../assets/glyphs/quill-192.png') },
  scroll: { 48: require('../../assets/glyphs/scroll-48.png'), 96: require('../../assets/glyphs/scroll-96.png'), 192: require('../../assets/glyphs/scroll-192.png') },
  waypoint: { 48: require('../../assets/glyphs/waypoint-48.png'), 96: require('../../assets/glyphs/waypoint-96.png'), 192: require('../../assets/glyphs/waypoint-192.png') },
  frost: { 48: require('../../assets/glyphs/frost-48.png'), 96: require('../../assets/glyphs/frost-96.png'), 192: require('../../assets/glyphs/frost-192.png') },
  target: { 48: require('../../assets/glyphs/target-48.png'), 96: require('../../assets/glyphs/target-96.png'), 192: require('../../assets/glyphs/target-192.png') },
  scales: { 48: require('../../assets/glyphs/scales-48.png'), 96: require('../../assets/glyphs/scales-96.png'), 192: require('../../assets/glyphs/scales-192.png') },
  crown: { 48: require('../../assets/glyphs/crown-48.png'), 96: require('../../assets/glyphs/crown-96.png'), 192: require('../../assets/glyphs/crown-192.png') },
  swords: { 48: require('../../assets/glyphs/swords-48.png'), 96: require('../../assets/glyphs/swords-96.png'), 192: require('../../assets/glyphs/swords-192.png') },
  book: { 48: require('../../assets/glyphs/book-48.png'), 96: require('../../assets/glyphs/book-96.png'), 192: require('../../assets/glyphs/book-192.png') },
  shield: { 48: require('../../assets/glyphs/shield-48.png'), 96: require('../../assets/glyphs/shield-96.png'), 192: require('../../assets/glyphs/shield-192.png') },
  spark: { 48: require('../../assets/glyphs/spark-48.png'), 96: require('../../assets/glyphs/spark-96.png'), 192: require('../../assets/glyphs/spark-192.png') },
  cup: { 48: require('../../assets/glyphs/cup-48.png'), 96: require('../../assets/glyphs/cup-96.png'), 192: require('../../assets/glyphs/cup-192.png') },
  feast: { 48: require('../../assets/glyphs/feast-48.png'), 96: require('../../assets/glyphs/feast-96.png'), 192: require('../../assets/glyphs/feast-192.png') },
  goblet: { 48: require('../../assets/glyphs/goblet-48.png'), 96: require('../../assets/glyphs/goblet-96.png'), 192: require('../../assets/glyphs/goblet-192.png') },
  mask: { 48: require('../../assets/glyphs/mask-48.png'), 96: require('../../assets/glyphs/mask-96.png'), 192: require('../../assets/glyphs/mask-192.png') },
  mountain: { 48: require('../../assets/glyphs/mountain-48.png'), 96: require('../../assets/glyphs/mountain-96.png'), 192: require('../../assets/glyphs/mountain-192.png') },
  temple: { 48: require('../../assets/glyphs/temple-48.png'), 96: require('../../assets/glyphs/temple-96.png'), 192: require('../../assets/glyphs/temple-192.png') },
  gate: { 48: require('../../assets/glyphs/gate-48.png'), 96: require('../../assets/glyphs/gate-96.png'), 192: require('../../assets/glyphs/gate-192.png') },
  stage: { 48: require('../../assets/glyphs/stage-48.png'), 96: require('../../assets/glyphs/stage-96.png'), 192: require('../../assets/glyphs/stage-192.png') },
  signpost: { 48: require('../../assets/glyphs/signpost-48.png'), 96: require('../../assets/glyphs/signpost-96.png'), 192: require('../../assets/glyphs/signpost-192.png') },
  page: { 48: require('../../assets/glyphs/page-48.png'), 96: require('../../assets/glyphs/page-96.png'), 192: require('../../assets/glyphs/page-192.png') },
  chair: { 48: require('../../assets/glyphs/chair-48.png'), 96: require('../../assets/glyphs/chair-96.png'), 192: require('../../assets/glyphs/chair-192.png') },
  door: { 48: require('../../assets/glyphs/door-48.png'), 96: require('../../assets/glyphs/door-96.png'), 192: require('../../assets/glyphs/door-192.png') },
  night: { 48: require('../../assets/glyphs/night-48.png'), 96: require('../../assets/glyphs/night-96.png'), 192: require('../../assets/glyphs/night-192.png') },
  ember: { 48: require('../../assets/glyphs/ember-48.png'), 96: require('../../assets/glyphs/ember-96.png'), 192: require('../../assets/glyphs/ember-192.png') },
  medal: { 48: require('../../assets/glyphs/medal-48.png'), 96: require('../../assets/glyphs/medal-96.png'), 192: require('../../assets/glyphs/medal-192.png') },
  'medal-blank': { 48: require('../../assets/glyphs/medal-blank-48.png'), 96: require('../../assets/glyphs/medal-blank-96.png'), 192: require('../../assets/glyphs/medal-blank-192.png') },
  ring: { 48: require('../../assets/glyphs/ring-48.png'), 96: require('../../assets/glyphs/ring-96.png'), 192: require('../../assets/glyphs/ring-192.png') },
  wax: { 48: require('../../assets/glyphs/wax-48.png'), 96: require('../../assets/glyphs/wax-96.png'), 192: require('../../assets/glyphs/wax-192.png') },
  wick: { 48: require('../../assets/glyphs/wick-48.png'), 96: require('../../assets/glyphs/wick-96.png'), 192: require('../../assets/glyphs/wick-192.png') },
};

/** Frames in each drawn strip (`InkDraw`), each 192px square, laid side by side. */
export const GLYPH_DRAW_FRAMES = 14;

/** The ceremony glyphs, painted stroke by stroke: one horizontal strip of frames each. */
export const GLYPH_DRAWS: Partial<Record<GlyphName, ImageSourcePropType>> = {
  'chest-open': require('../../assets/glyphs/chest-open-draw-192.png'),
  flame: require('../../assets/glyphs/flame-draw-192.png'),
  seal: require('../../assets/glyphs/seal-draw-192.png'),
  medal: require('../../assets/glyphs/medal-draw-192.png'),
};

/** The ground each place stands on, baked apart so it takes its own tint (see `Places`). */
export const GLYPH_GROUNDS: Partial<Record<GlyphName, Record<(typeof GLYPH_PIXELS)[number], ImageSourcePropType>>> = {
  gate: { 48: require('../../assets/glyphs/gate-ground-48.png'), 96: require('../../assets/glyphs/gate-ground-96.png'), 192: require('../../assets/glyphs/gate-ground-192.png') },
  stage: { 48: require('../../assets/glyphs/stage-ground-48.png'), 96: require('../../assets/glyphs/stage-ground-96.png'), 192: require('../../assets/glyphs/stage-ground-192.png') },
  signpost: { 48: require('../../assets/glyphs/signpost-ground-48.png'), 96: require('../../assets/glyphs/signpost-ground-96.png'), 192: require('../../assets/glyphs/signpost-ground-192.png') },
  chair: { 48: require('../../assets/glyphs/chair-ground-48.png'), 96: require('../../assets/glyphs/chair-ground-96.png'), 192: require('../../assets/glyphs/chair-ground-192.png') },
  door: { 48: require('../../assets/glyphs/door-ground-48.png'), 96: require('../../assets/glyphs/door-ground-96.png'), 192: require('../../assets/glyphs/door-ground-192.png') },
  night: { 48: require('../../assets/glyphs/night-ground-48.png'), 96: require('../../assets/glyphs/night-ground-96.png'), 192: require('../../assets/glyphs/night-ground-192.png') },
  ember: { 48: require('../../assets/glyphs/ember-ground-48.png'), 96: require('../../assets/glyphs/ember-ground-96.png'), 192: require('../../assets/glyphs/ember-ground-192.png') },
};
