// Generated by scripts/gen-banner.js — do not edit; rerun the script instead.

import type { ImageSourcePropType } from 'react-native';

/** The wax seal on its ribbons. The pressed face is this share of its width. */
export const BANNER_SEAL: ImageSourcePropType = require('../../assets/banner/seal.png');
export const SEAL_PRESS_SHARE = 0.41;
export const SEAL_WAX_SHARE = 0.6;

/** The sun round the seal: a white mask, tinted by the chat's Unsealing. */
export const BANNER_RING: ImageSourcePropType = require('../../assets/banner/ring.png');
