// Generated by scripts/gen-satchel.js — rerun it, never edit this.
import type { ImageSourcePropType } from 'react-native';

export type SatchelObject = 'candles' | 'arrows' | 'lantern' | 'oath' | 'key' | 'word' | 'honour' | 'seals' | 'card';

/** Each object the Satchel holds, painted (128px, shown at 32pt). */
export const SATCHEL_IMAGES: Record<SatchelObject, ImageSourcePropType> = {
  candles: require('../../assets/satchel/candles.png'),
  arrows: require('../../assets/satchel/arrows.png'),
  lantern: require('../../assets/satchel/lantern.png'),
  oath: require('../../assets/satchel/oath.png'),
  key: require('../../assets/satchel/key.png'),
  word: require('../../assets/satchel/word.png'),
  honour: require('../../assets/satchel/honour.png'),
  seals: require('../../assets/satchel/seals.png'),
  card: require('../../assets/satchel/card.png'),
};
