// The Ulzii Design Language asset registry. Generated by scripts/gen-ornaments.js —
// rerun that script to regenerate; never hand-edit the PNGs.
export const ORNAMENTS = {
  knotGold: require('../assets/ornaments/knot_gold.png'),
  knotDim: require('../assets/ornaments/knot_dim.png'),
  knotEmber: require('../assets/ornaments/knot_ember.png'),
  knotBossEmber: require('../assets/ornaments/knot_boss_ember.png'),
  sigilBond: require('../assets/ornaments/sigil_bond.png'),
  sigilFate: require('../assets/ornaments/sigil_fate.png'),
  sigilKinship: require('../assets/ornaments/sigil_kinship.png'),
  fretGold: require('../assets/ornaments/fret_gold.png'),
  fretDark: require('../assets/ornaments/fret_dark.png'),
} as const;

// fret_gold/fret_dark are 1610x50 px. Displayed at FRET_DISPLAY_HEIGHT, an undistorted
// strip is FRET_DISPLAY_WIDTH wide — size Images with these and clip in the container.
export const FRET_ASPECT = 1610 / 50;
