// scripts/gen-glyphs.js — rasterizes the hand-cut glyph set (components/ui/Glyph.tsx) to PNGs.
//
// The drawings stay where they are: this reads the GLYPHS table, STROKE and DOT straight out of
// Glyph.tsx, so that file is still the one place a glyph is cut. What changes is how the app
// shows one. Drawn live as react-native-svg, every glyph on Android was its own view rasterized
// on the CPU into its own bitmap whenever it appeared — 23 of them made up much of the Hearth's
// 400ms opening frame on the Galaxy A51 (2026-10-03). As a white PNG tinted at draw time it is a
// texture the GPU already has.
//
// Rendered with canvaskit-wasm (Skia, already installed for the web build), so square caps and
// mitred corners are drawn by the same library that draws them on device. Three sizes per glyph
// so nothing is ever shrunk more than 2x on screen (bilinear scaling past that loses thin lines).
//
// Rerun with: node scripts/gen-glyphs.js   (writes assets/glyphs/*.png and components/ui/glyphImages.ts)

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'components', 'ui', 'Glyph.tsx');
const OUT_DIR = path.join(ROOT, 'assets', 'glyphs');
const MAP_FILE = path.join(ROOT, 'components', 'ui', 'glyphImages.ts');
const SIZES = [48, 96, 192];
const VIEWBOX = 24;

function readCuts() {
  const src = fs.readFileSync(SOURCE, 'utf8');
  const literal = src.match(/(?:export )?const GLYPHS: Record<GlyphName, Cuts> = (\{[\s\S]*?\n\});/);
  const stroke = src.match(/export const STROKE = ([\d.]+);/);
  const dot = src.match(/(?:export )?const DOT = ([\d.]+);/);
  if (!literal || !stroke || !dot) throw new Error('Glyph.tsx no longer has the shape this script reads');
  // The table is a plain object literal (comments and all), so it evaluates as JavaScript.
  const glyphs = new Function(`return (${literal[1]});`)();
  return { glyphs, stroke: Number(stroke[1]), dot: Number(dot[1]) };
}

async function main() {
  const CanvasKitInit = require('canvaskit-wasm/bin/canvaskit.js');
  const CK = await CanvasKitInit({ locateFile: (f) => require.resolve(`canvaskit-wasm/bin/${f}`) });
  const { glyphs, stroke, dot } = readCuts();
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const line = new CK.Paint();
  line.setAntiAlias(true);
  line.setColor(CK.WHITE);
  line.setStyle(CK.PaintStyle.Stroke);
  line.setStrokeWidth(stroke);
  line.setStrokeCap(CK.StrokeCap.Square);
  line.setStrokeJoin(CK.StrokeJoin.Miter);
  const fill = new CK.Paint();
  fill.setAntiAlias(true);
  fill.setColor(CK.WHITE);
  fill.setStyle(CK.PaintStyle.Fill);

  const names = Object.keys(glyphs);
  for (const name of names) {
    const { lines = [], rings = [], dots = [] } = glyphs[name];
    for (const px of SIZES) {
      const surface = CK.MakeSurface(px, px);
      const canvas = surface.getCanvas();
      canvas.clear(CK.TRANSPARENT);
      canvas.scale(px / VIEWBOX, px / VIEWBOX);
      for (const d of lines) {
        const p = CK.Path.MakeFromSVGString(d);
        if (!p) throw new Error(`${name}: unreadable path ${d}`);
        canvas.drawPath(p, line);
        p.delete();
      }
      for (const [cx, cy, r] of rings) canvas.drawCircle(cx, cy, r, line);
      for (const [cx, cy] of dots) canvas.drawRect(CK.XYWHRect(cx - dot / 2, cy - dot / 2, dot, dot), fill);
      const image = surface.makeImageSnapshot();
      fs.writeFileSync(path.join(OUT_DIR, `${name}-${px}.png`), Buffer.from(image.encodeToBytes()));
      image.delete();
      surface.delete();
    }
  }

  const entries = names.map((n) => `  ${n}: { ${SIZES.map((s) => `${s}: require('../../assets/glyphs/${n}-${s}.png')`).join(', ')} },`);
  fs.writeFileSync(MAP_FILE, [
    '// Generated by scripts/gen-glyphs.js from the GLYPHS table in ./Glyph.tsx — rerun it, never edit this.',
    "import type { ImageSourcePropType } from 'react-native';",
    "import type { GlyphName } from './Glyph';",
    '',
    `/** The pixel sizes each glyph is baked at; \`Glyph\` picks the smallest that covers the screen size. */`,
    `export const GLYPH_PIXELS = [${SIZES.join(', ')}] as const;`,
    '',
    `export const GLYPH_IMAGES: Record<GlyphName, Record<(typeof GLYPH_PIXELS)[number], ImageSourcePropType>> = {`,
    ...entries,
    '};',
    '',
  ].join('\n'));
  console.log(`${names.length} glyphs x ${SIZES.length} sizes`);
}

main().catch((e) => { console.error(e); process.exit(1); });
