// Generated by scripts/gen-cliff.js — do not edit; rerun the script instead.

import type { ImageSourcePropType } from 'react-native';

/** The rock face The Ascent is climbed on, stretched to the card's width. */
export const CLIFF_IMAGE: ImageSourcePropType = require('../../assets/cliff/cliff.png');

/** The drawing's height in points, at any width. */
export const ASCENT_HEIGHT = 420;

/** Each tier's socket, Garnet first, as [x / width, y / height]. */
export const ASCENT_STOPS: readonly (readonly [number, number])[] = [[0.26,0.8857],[0.7,0.7524],[0.3,0.6143],[0.69,0.4738],[0.33,0.3357],[0.6,0.2048]];
