// Generated by scripts/gen-gems.js — rerun it, never edit this.
import type { ImageSourcePropType } from 'react-native';
import type { GemTier } from '../../models/user';

/** The pixel sizes each stone's still is baked at; the badge picks the smallest that covers its size. */
export const GEM_STILL_PIXELS = [64, 128, 256] as const;
/** The cell sizes of the sway sheets. */
export const GEM_SWAY_PIXELS = [128, 256] as const;
/** A sway sheet holds this many poses, left to right then down, this many to a row. */
export const GEM_SWAY_FRAMES = 24;
export const GEM_SWAY_COLS = 6;

export const GEM_IMAGES: Record<GemTier, {
  still: Record<(typeof GEM_STILL_PIXELS)[number], ImageSourcePropType>;
  sway: Record<(typeof GEM_SWAY_PIXELS)[number], ImageSourcePropType>;
}> = {
  Garnet: {
    still: { 64: require('../../assets/gems/garnet-still-64.png'), 128: require('../../assets/gems/garnet-still-128.png'), 256: require('../../assets/gems/garnet-still-256.png') },
    sway: { 128: require('../../assets/gems/garnet-sway-128.png'), 256: require('../../assets/gems/garnet-sway-256.png') },
  },
  Opal: {
    still: { 64: require('../../assets/gems/opal-still-64.png'), 128: require('../../assets/gems/opal-still-128.png'), 256: require('../../assets/gems/opal-still-256.png') },
    sway: { 128: require('../../assets/gems/opal-sway-128.png'), 256: require('../../assets/gems/opal-sway-256.png') },
  },
  Amethyst: {
    still: { 64: require('../../assets/gems/amethyst-still-64.png'), 128: require('../../assets/gems/amethyst-still-128.png'), 256: require('../../assets/gems/amethyst-still-256.png') },
    sway: { 128: require('../../assets/gems/amethyst-sway-128.png'), 256: require('../../assets/gems/amethyst-sway-256.png') },
  },
  Sapphire: {
    still: { 64: require('../../assets/gems/sapphire-still-64.png'), 128: require('../../assets/gems/sapphire-still-128.png'), 256: require('../../assets/gems/sapphire-still-256.png') },
    sway: { 128: require('../../assets/gems/sapphire-sway-128.png'), 256: require('../../assets/gems/sapphire-sway-256.png') },
  },
  Ruby: {
    still: { 64: require('../../assets/gems/ruby-still-64.png'), 128: require('../../assets/gems/ruby-still-128.png'), 256: require('../../assets/gems/ruby-still-256.png') },
    sway: { 128: require('../../assets/gems/ruby-sway-128.png'), 256: require('../../assets/gems/ruby-sway-256.png') },
  },
  Emerald: {
    still: { 64: require('../../assets/gems/emerald-still-64.png'), 128: require('../../assets/gems/emerald-still-128.png'), 256: require('../../assets/gems/emerald-still-256.png') },
    sway: { 128: require('../../assets/gems/emerald-sway-128.png'), 256: require('../../assets/gems/emerald-sway-256.png') },
  },
};
