// Generated by scripts/gen-carvings.js — do not edit; rerun the script instead.

import type { ImageSourcePropType } from 'react-native';

/** One frieze per room: a white alpha mask, tinted by `Carvings`. */
export const CARVING_IMAGES: Record<string, ImageSourcePropType> = {
  gate: require('../../assets/carvings/gate.png'),
  road: require('../../assets/carvings/road.png'),
  tavern: require('../../assets/carvings/tavern.png'),
  hearth: require('../../assets/carvings/hearth.png'),
  forge: require('../../assets/carvings/forge.png'),
  hall: require('../../assets/carvings/hall.png'),
  deep: require('../../assets/carvings/deep.png'),
};

/** The rooms whose frieze is painted in ochre rather than pecked into the stone. */
export const PAINTED_ROOMS: readonly string[] = ['deep'];

/** Width over height of every frieze. */
export const CARVING_ASPECT = 3;
