// Generated by scripts/gen-stones.js — do not edit; rerun the script instead.

import type { ImageSourcePropType } from 'react-native';

/** Width over height of each bake, in the order `STONE_IMAGES` lists them. */
export const STONE_ASPECTS = [1.4,2.2,3.4,5,7.5] as const;

/** [stone][aspect index][variant]. */
export const STONE_IMAGES: Record<'sand' | 'slate', ImageSourcePropType[][]> = {
  sand: [
    [require('../../assets/stones/sand-0-0.png'), require('../../assets/stones/sand-0-1.png'), require('../../assets/stones/sand-0-2.png')],
    [require('../../assets/stones/sand-1-0.png'), require('../../assets/stones/sand-1-1.png'), require('../../assets/stones/sand-1-2.png')],
    [require('../../assets/stones/sand-2-0.png'), require('../../assets/stones/sand-2-1.png'), require('../../assets/stones/sand-2-2.png')],
    [require('../../assets/stones/sand-3-0.png'), require('../../assets/stones/sand-3-1.png'), require('../../assets/stones/sand-3-2.png')],
    [require('../../assets/stones/sand-4-0.png'), require('../../assets/stones/sand-4-1.png'), require('../../assets/stones/sand-4-2.png')],
  ],
  slate: [
    [require('../../assets/stones/slate-0-0.png'), require('../../assets/stones/slate-0-1.png'), require('../../assets/stones/slate-0-2.png')],
    [require('../../assets/stones/slate-1-0.png'), require('../../assets/stones/slate-1-1.png'), require('../../assets/stones/slate-1-2.png')],
    [require('../../assets/stones/slate-2-0.png'), require('../../assets/stones/slate-2-1.png'), require('../../assets/stones/slate-2-2.png')],
    [require('../../assets/stones/slate-3-0.png'), require('../../assets/stones/slate-3-1.png'), require('../../assets/stones/slate-3-2.png')],
    [require('../../assets/stones/slate-4-0.png'), require('../../assets/stones/slate-4-1.png'), require('../../assets/stones/slate-4-2.png')],
  ],
};

export const STONE_SHADOW: ImageSourcePropType = require('../../assets/stones/shadow.png');
